package-lock.json, package.json, src/App.vue, src/api/tmdb.js, src/router/index.js, src/views/TestPage.vue
- TMDB Api 연동을 위한 tmdb.js 제작 및 간단한 서치 페이지 제작
- API KEY는 .env 파일 만들어서 자기 api키 넣어서 사용
- #2
=> Feat: TMDB API

db.json
- db.sjon파일 생성 (유저관련 정보)
- 현재는 x
- 예: Feat #6
=> #6 feat:db.sjon 파일 생성

src/router/index.js, src/views/DetailPage.vue, src/views/FavoritesPage.vue, src/views/HomePage.vue, src/views/LoginPage.vue, src/views/NotFoundPage.vue, src/views/ProfilePage.vue, src/views/SearchPage.vue, src/views/SignupPage.vue
=> Feat: 라우터 페이지 및 404 설정 추가

package-lock.json, package.json, src/main.js
=> Chore: 부트스트랩 추가

src/assets/main.css, src/components/layouts/Footer.vue
- main.css에 주요 색상 코드 저장
- 풋터 코드에 적용
- #11
=> Style: 컬러 코드 변수화 및 적용

src/assets/main.css, src/components/layouts/Footer.vue, src/components/layouts/Navbar.vue
- nav바 작성(store 완성 후 수정 예정)
- 한글 폰트 추가
- 인라인 색상 스타일 수정
- #11
=> Chore: Navbar 추가

stores/userStore.js
- 유저스토어 추가
- 혹시 안되는 부분 있는지 확인 후 안되는 부분 있다면 말씀해주세요 
- Feat #16
=> Feat: 새로운 기능 추가

src/components/MovieCard.vue
- 영화 포스터 카드 스타일 수정
- 예: Closes #18
=> Style: 카드 스타일 수정

src/views/HomePage.vue
- Home 페이지 추가
- 서치바 추가, 기능 구현 완료
- 추천 인기 영화 10선 디스플레이 완료
- #20
=> Feat: Home 페이지 추가

src/api/tmdb.js, src/components/Pagination.vue, src/components/layouts/DefaultLayout.vue, src/views/SearchPage.vue
- 서치 페이지 기능 추가
- 전체 화면 높이 조절 스타일링 추가
- TMDB 검색 시 여러 페이지 결과 가져올 수 있도록 수정 
- 페이지네이션 컴포넌트 추가
- #25
=> Feat: SearchPage

src/components/MovieCard.vue, src/views/DetailPage.vue
- 영화 디테일 페이지 틀 구현
- 카드 컴포넌트 수정: 해당 영화의 디테일 페이지로 이동하는 기능 추가
- #27
=> Feat: Detail Page 추가

src/views/LoginPage.vue, src/views/SignupPage.vue
- 로그인 및 회원가입 디자인 변경 및 회원가입화면에서 로그인 화면으로 되돌아가기 버튼 추가
- 
- 예: Style #33
=> Style: 디자인 변경

src/views/LoginPage.vue
- 로그인 페이지에서 입력 시 검은색 border, inline 제거함
- 우선은 로그인 기능이 구현 안되어있기에 입력창 클릭 시 비우는 기능은 안 넣었습니다!
로그인 기능 들어가면 입력창 비우는 기능도 추가해주세요!
- #13
=> Style: 입력창 focus 시 border, outline 제거

vite.config.js
- porxy 설정
- 혹시 위의 변경사항으로 인해 오류 발생하는 점 있다면 말씀해주세요!
- 예: Refactor #36
=> Refactor: proxy 설정

src/views/LoginPage.vue, src/views/SignupPage.vue
- 유저 로그인 및 회원가입 기능 연결완료
- 회원가입 완료 시, alert 통해 완료했음을 알리고 로그인 페이지로 이동
- 로그인 완료시 home 페이지로 이동
- 예: Feat #13
=> Feat: 로그인/회원가입 기능 추가

src/stores/favoritesStore.js
- 위시리스트 스토어 완성 
- 테스트 후 문제점이 있다면 말씀해주세요!
- 예: Feat #40
=> Feat: 위시리스트 스토어

src/stores/favoritesStore.js
- 변경한 기능 요약
- 리뷰어에게 요청사항이 있다면 작성
- 예: Closes #1, Fixes #2
=> Feat: 유저스토어 완성

src/components/layouts/Navbar.vue
- Navbar에 로그인 케이스에서 로그아웃 버튼 기능 추가
- Closes #11
=> Feat: Navbar에 로그아웃 기능 추가

src/stores/favoritesStore.js, src/views/DetailPage.vue
- FavoriteStore 수정
- 비 로그인시 찜 버튼 기능 활성 안됨
- 이슈 수정했습니다. 확인 부탁 드립니다. 문제 발생 시 말씀해주세요!
- #40 
- #27
=> Fix: 로그인 후 찜버튼 작동 오류 수정

db.json
- db.json에 테스트 리뷰 및 위시 리스트 목록 추가
- #46
=> Chore: 테스트 데이터 추가

src/components/profileComponets/MyReview.vue, src/components/profileComponets/UserInfo.vue, src/views/ProfilePage.vue
- profilePage 및 컴포넌트 추가 및 완성
- 리뷰어에게 요청사항이 있다면 작성
- 예: Feat #50
=> feat: profilePage 및 컴포넌트

src/views/FavoritesPage.vue
- 변경한 기능 요약
- 리뷰어에게 요청사항이 있다면 작성
- 예: Feat #51
=> feat: favoritespage 완성

src/stores/favoritesStore.js
- refactor: favoritesStore 수정
- 리뷰어에게 요청사항이 있다면 작성
- 예: Closes #1, Fixes #2
=> refactor: favoritesStore 수정

src/router/index.js, src/stores/userStore.js
=> Feat: 라우터 가드 설정

src/stores/favoritesStore.js, src/stores/ratingStore.js, src/stores/userStore.js, src/views/DetailPage.vue
=> Chore: 데모 설정 수정

src/views/DetailPage.vue
비로그인 상태에서 찜 기능 클릭 시 오류 방지 및 안내 메시지 추가
=> Fix: 비로그인 상태에서 찜 기능 클릭 시 오류 방지 및 안내 메시지 추가
